sudo: required

services:
  - docker

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

before_install:
  - docker run -d -p 8080:8080 --name eureka netflixoss/eureka:1.1.147
  - docker ps -a
  - curl -v "http://127.0.0.1:8080/eureka/v2/apps"

after_script:
  - npm run coveralls

cache:
  directories:
    - node_modules
