sudo: required

services:
  - docker

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

after_script:
  - npm run coveralls
  - docker run -d -p 8080:8080 --name eureka netflixoss/eureka:1.3.1
  - docker ps -a
  - echo "waiting 60 seconds for server to fully start"
  - sleep 60
  - curl -L -v "http://localhost:8080/eureka"

cache:
  directories:
    - node_modules
