sudo: required

services:
  - docker

language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs"

before_install:
  - docker run -d -p 8080:8080 --name eureka netflixoss/eureka:1.3.1
  - docker ps -a
  - echo "waiting 60 seconds"
  - sleep 60
  - curl -L -v "http://localhost:8080/eureka/v2/apps" -H "Accept: application/json"

after_script:
  - npm run coveralls

cache:
  directories:
    - node_modules
